name: Publish All Packages
on:
  push:
    branches:
      - main
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v1
        with:
          node-version: 14.3.0
      - run: git config --global user.email "example@gmail.com"
      - run: git config --global user.name "Builder"
      - name: Install Packages
        run: yarn
      - name: Publish Win
        run: yarn dist:win
      - name: Publish Mac
        run: yarn dist:mac
      - name: Upload mac artifact
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.dmg'
  